In [8]:
#add the two matrix
X=[[1,2,3],[4,5,6],[7,8,9]]
Y=[[9,8,7],[6,5,4],[3,2,1]]
res=[[0,0,0],[0,0,0],[0,0,0]]
for i in range (len(X)):
    for j in range(len(X[0])):
        res[i][j]=X[i][j]+Y[i][j]
for r in res:        
    print(r)        

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [9]:
X=[[1,2,3],[4,5,6],[7,8,9]]
Y=[[9,8,7],[6,5,4],[3,2,1]]
res=[[0,0,0],[0,0,0],[0,0,0]]
for i in range (len(X)):
    for j in range(len(Y)):
        res[i][j]=X[i][j]+Y[i][j]       
print(res)        

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


In [12]:
X=[[1,2,3],[4,5,6],[7,8,9]]
Y=[[9,8,7],[6,5,4],[3,2,1]]
res=[[X[i][j]+Y[i][j] for j in range (len(X[0]))] for i in range (len(X))]
for r in res:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [13]:
#multiplication
X=[[1,2,3],[4,5,6],[7,8,9]]
Y=[[9,8,7],[6,5,4],[3,2,1]]
res=[[0,0,0],[0,0,0],[0,0,0]]
for i in range (len(X)):
    for j in range(len(X[0])):
        res[i][j]=X[i][j]*Y[i][j]
for r in res:        
    print(r)    

[9, 16, 21]
[24, 25, 24]
[21, 16, 9]


In [14]:
X=[[1,2,3],[4,5,6],[7,8,9]]
Y=[[9,8,7],[6,5,4],[3,2,1]]
res=[[0,0,0],[0,0,0],[0,0,0]]
for i in range (len(X)):
    for j in range(len(Y)):
        res[i][j]=X[i][j]*Y[i][j]       
print(res)        

[[9, 16, 21], [24, 25, 24], [21, 16, 9]]


In [15]:
X=[[1,2,3],[4,5,6],[7,8,9]]
Y=[[9,8,7],[6,5,4],[3,2,1]]
res=[[X[i][j]*Y[i][j] for j in range (len(X[0]))] for i in range (len(X))]
for r in res:
    print(r)

[9, 16, 21]
[24, 25, 24]
[21, 16, 9]


In [19]:
#addition and substraction
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,7]])
print(a)
print(b)


[[1 2]
 [3 4]]
[[4 5]
 [6 7]]


In [20]:
print(np.add(a,b))

[[ 5  7]
 [ 9 11]]


In [18]:
print(np.subtract(a,b))

[[-3 -3]
 [-3 -3]]


In [21]:
#to find the transpose
m=[[1,2],[3,4],[5,6]]
for row in m:
    print (row)

[1, 2]
[3, 4]
[5, 6]


In [22]:
res=[[m[j][i] for j in range (len(m))] for i in range (len(m[0]))]
for r in res:
    print(r)

[1, 3, 5]
[2, 4, 6]


In [25]:
import numpy as np
m=np.array([[1,2,3],[4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [26]:
print(m.T)

[[1 4]
 [2 5]
 [3 6]]
